filter:
    excluded_paths: ["Tests/Fixtures/*", "Tests/*/Fixture/*"]

default_config:
    verify_php_doc_comments: true
    doc_comment_fixes: true
    fabpot_cs_fixer:
        enabled: true
        level: PSR-2
    psr0_compliance: true
    checkstyle: true
    loops_must_use_braces: true
    simplify_boolean_return: true
    composer_config_check:
        publish_checks: true
        level: warning
    reflection_fixes: true

path_configs:
    tests:
        paths: [Tests/*]
        verify_php_doc_comments: false
        doc_comment_fixes: false
        fabpot_cs_fixer: false
        psr0_compliance: false
        checkstyle: false
        phpunit_checks: true
